replicaCount: 2

image:
  repository: react-clean
  tag: staging
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30008

ingress:
  enabled: true
  className: nginx
  host: staging.local
  path: /
  pathType: Prefix

env:
  APP_ENV: staging