replicaCount: 1

image:
  repository: react-clean
  tag: v1
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30007

ingress:
  enabled: true
  className: nginx
  host: dev.local
  path: /
  pathType: Prefix

env:
  APP_ENV: development